### ISSUE TITLE
can i get to know the logic in this function of extract_class_bounding_boxes

### ISSUE THREAD

**Issue by Hrishkesh** [antoinedelplace/Chargrid#5]
i have doubt in this part of section
         for index, row in pd_boxes.iterrows():
             #Classes of type string
             if cosine_similarity(vectorized_text[0].reshape(1, -1) 
 vectorized_text[index+nb_classes].reshape(1, -1))[0][0] > cosine_similarity_threshold:
            gt_pd = add_row_gt_pd(row, 3, gt_pd)  **#you passed here class as 3**
        
             if cosine_similarity(vectorized_text[2].reshape(1, -1), vectorized_text[index+nb_classes].reshape(1, -1))[0][0] > cosine_similarity_threshold:
            gt_pd = add_row_gt_pd(row, 2, gt_pd)  **#you passed here the class as 2** 

i din't get the part as class 2 is date

nb_classes = ['company','date','address','total'] as the order is 1,2,3,4 but for the #classes of type string is 1 and 3

**Comment by antoinedelplace** [comment]
Yes you are right the class label does not follow the order ['company', 'date', 'address', 'total'].

I changed the order so that it goes from the less certain to the most certain. I did this because I want a unique class label (and the most certain one) for each box.

Here is the order : ['total', 'address', 'company', 'date']
